
spring:
  application:
    name: test
#  jpa:
  #  database-platform: org.hibernate.dialect.PostgreSQLDialect
  #  show-sql: 'true'
  #  hibernate:
   #   ddl-auto: update
   #   naming:
      #  implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      #  physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
server:
  port: '8085'
